config/routes.rb
RubyHwJdm::Application.routes.draw do
 
  devise_for :users
  resources :widgets

    root :to => "pages#index"
    match '/index',         :to=> 'pages#index'
    match '/stream',        :to => 'pages#stream'
    match '/help',          :to => 'pages#help'
    match '/login',         :to =>'users#login'
    match '/anmeldung',     :to=> 'users#signup'
    match '/show',          :to=> 'users#show'
    match '/about',         :to => 'pages#about'
    match '/dashboard',     :to => 'dashboards#index'
    match '/config',        :to => 'dashboards#konfiguration'
    match '/calendar',      :to => 'calendar#calendar'
    match '/new_date',      :to => 'calendar#new_date'

  
  

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  belongs_to :user
  has_many :widgets
  
end

app/models/sourcetype.rb
class Sourcetype < ActiveRecord::Base
  has_many :widgets
end

app/models/stream.rb
class Stream < ActiveRecord::Base
end

app/models/tasks.rb
class Tasks < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :confirmable, :timeoutable and :activatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
  end

app/models/widget.rb
class Widget < ActiveRecord::Base
  belongs_to :sourcetype
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper :all
  
  before_filter :prepare_for_mobile
  
  def after_sign_in_path_for(resource)
    if mobile_device?
      "/dashboard"
    else
      "/stream"
    end
   
  end
  
  private
  
    def user_is_logged_in?
      if !current_user.nil?
        current_user
      else
        flash[:error] = "Bitte erst einloggen!"
        redirect_to new_user_session_path
      end
    end
  
    def mobile_device?
      if session[:mobile_param]
        session[:mobile_param] == "1"
      else
        request.user_agent =~ /Mobile|webOS/
      end
    end
    
    helper_method :mobile_device?
    
    def prepare_for_mobile
      session[:mobile_param] = params[:mobile] if params[:mobile]
      request.format = :mobile if mobile_device?
    end
    
    def authenticate
      if current_user
        
      else
      redirect_to new_user_registration_path
      end
    end

end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
    before_filter :authenticate

  def calendar
  @title = "Kalender"
  @date = params[:month] ? Date.parse(params[:month]) : Date.today
  @tasks = Tasks.where(:user_email == current_user.email).all
  
  if params[:iddelete]
    @id = params[:iddelete]
   Tasks.delete(@id)
   flash[:success] = "Termin geloescht"
   redirect_to calendar_path
   end
  end
  
   
 def new_date
    @title = "Neuer Termin"
    
    if params[:tasks]
      params[:tasks][:user_email] = current_user.email
      @task = Tasks.new(params[:tasks])
        if @task.save
          flash[:success] = "Termin gespeichert!"
          redirect_to calendar_path
        end
    else
      @task = Tasks.new
    end
 end
 
end 
 
 

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
      before_filter :authenticate

  def index
    @title = "Dashboard"
    @dashboard = Dashboard.find_by_user_id(current_user.id)

    if @dashboard.nil?
      @dashboard = Dashboard.new({ :user_id => current_user.id })
      @dashboard.save
    end
    
    @widgets = @dashboard.widgets


  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_filter :authenticate, :only => [:stream]

  
  def index
    @title = "Home"
  end

  def stream
    @title = "Deine Streams"
    video = "/video/"
    stream = Stream.find_by_id(1+rand(Stream.count))
    
    if !stream.nil?
      real_url = stream.url
    else
      real_url = ""
    end
    
    @video_path = video + real_url
  end
  
  def help
    @title = "Help"
  end
  
  def about
    @title = "About"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
  @title = "Show"
end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
      before_filter :authenticate

  
  def index
    @title = "Widgets"
    dashboard = Dashboard.find_by_user_id(current_user.id)
    @widgets = dashboard.widgets
    
  end
  
  def new
    @title = "Neues Widget anlegen"
    @widget = Widget.new
    @sourcetypes = Sourcetype.all
  end
  
  def create
    dashboard = Dashboard.find_by_user_id(current_user.id)
    
    params[:widget][:dashboard_id] = dashboard.id
    @widget = Widget.new(params[:widget])
    if @widget.save
      flash[:success] = "Widget gespeichert!"
      redirect_to widgets_path
    end
  end
  
  def show
   if params[:delid]
       @deleteid = params[:id]
      Widget.delete(@deleteid)
      flash[:success] = "Erfolgreich geloescht!"
      redirect_to dashboard_path
    end
  end
  
  def destroy
  
      if Widget.delete(@deleteid)
      flash[:success] = "Erfolgreich geloescht!"
      redirect_to dashboard_path
    
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
    def getWidgetContent(widget)
      if widget.sourcetype.name == "RSS" && widget.sourceurl != nil
        # Quelle: http://simple-rss.rubyforge.org/
        
        # quelle: http://banusha.blogspot.com/2009/10/ruby-on-rails-try-catch-fainally-block.html
        begin
          rss = SimpleRSS.parse open(widget.sourceurl)
        
          if rss.items        
            if mobile_device?
              output = '<h2 style="margin-left: 0px;">' + widget.sourcename + '</h2>'
            else
              output = '<h2 style="margin-left: 0px;">' + image_tag('bullet_toggle_plus.png', { :onclick => "new Effect.toggle('" + widget.id.to_s + "');"}) + widget.sourcename + '</h2>'
            end
            
            output += "<div id='" + widget.id.to_s + "'>"        
            rss.items[0..4].each do |i|
              if mobile_device?
                output += "<h3>" + link_to(i.title, i.link, { :rel => "external" }) + "</h3>"
              else
                output += "<h3>" + link_to(i.title, i.link, { :target => "_blank" }) + "</h3>"
              end
            end
            output += '</div>'
            
            # Quelle: http://blog.emeidi.com/2011/02/25/ruby-on-rails-3-kleinigkeiten/
            output.html_safe
          end
        rescue
          flash[:error] = "Konnte Feed nicht abrufen. Bitte ueberpruefe die URL!"
        end
      end
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/calendar/calendar.html.erb
<div id="calendar">
  <%= @first_day_of_week %>
  <h2 id="month">
     <%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m-%d") %>
    <%= h @date.strftime("%B %Y") %>
 <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m-%d") %>
  </h2>
  <p class="navioben"><%= link_to "Neuen Termin anlegen", new_date_path%><br>
  
  
  <% calendar_for (@tasks, {:year => @date.year, :month => @date.month}) do |t| %>
    
    <%= t.head('So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa') %>
    <%  t.day(:day_method => :task_date) do |date, tasks| %>
        <%= date.day %>
      <ul>
        <% for task in tasks %>
          <li><%=h(task.task_title)%> </li>
          <li><%= link_to "delete", calendar_path(:iddelete => task.id), :confirm => "Wirklich loeschen?"%>
        <% end %>
      </ul>
	<% end %>
  <% end %>
</div>

app/views/calendar/new_date.html.erb
<h1> Neuer Termin </h1>

<%= puts params[:task] %>
<fieldset>
<legend>Termin anlegen: </legend>
<% form_for @task, :url=> {:action =>:new_date}  do |f| %>

<div class = "field">
<p><%= f.label "Datum"%></label>
<%= f.text_field :task_date %></p>

<p><%= f.label "Eintrag"%></label>
<%= f.text_field :task_title %></p>

</div>
<div class="actions">
<%= f.submit "Speichern" %>
</div>
</fieldset>
<%end%>

app/views/dashboards/index.html.erb
<h1>Dein Dashboard</h1>

<p><%= link_to 'Widgets bearbeiten', widgets_path %></p>

<div class="container">
<% if !@widgets.nil? %>
	<% @widgets.each do |w| %>
	<div class="widget">
	<div class="widget_content">
	<%= getWidgetContent(w) %>
	</div>
	</div>
	<% end %>
<% end %>
</div>

app/views/dashboards/index.mobile.erb
<div class="container">
<% if !@widgets.nil? %>
	<% @widgets.each do |w| %>
	
	<ul>
		<li><%= getWidgetContent(w) %></li>
	</ul>	
	
	
	<% end %>
<% end %>
</div>

app/views/dashboards/konfiguration.html.erb
empty

app/views/layouts/_footer.html.erb
<footer> <p align = center> created by: Julian, Dirk, Max<br />
 
</footer>
 <% if Rails.env.development? %>
  	<div style="text-align: left;">
	  	<%= debug(params) %>
	  	<%= debug(session) %>
  	</div>
  <% end %>

app/views/layouts/_header.html.erb
<header>

<div class = "navioben">     
<ul>
   
	<li><%= link_to "Home", root_path %></li>
	<li> | </li>
	<li><%= link_to "About", about_path %></li>
	<li> | </li>
	<%if user_signed_in?%>
		<li><%= link_to "Logout", destroy_user_session_path %></li>
	<%else%>
		<li><%= link_to "Login", new_user_session_path %></li>
	<%end%>
     
    <li> | </li>
     
	<% if mobile_device? %>
		<li><%= link_to 'Full Site', :mobile => 0 %></li>
	<% else %>
		<li><%= link_to 'Mobile Site', :mobile => 1 %></li>
	<% end %>       
</ul>

</header>

app/views/layouts/_navileft.html.erb
<navileft>
  
<ul>
    <%if user_signed_in? %>
    <li><%= link_to "Stream", stream_path %></li>
    <li><%= link_to "Dashboard", dashboard_path %></li>
    <li><%= link_to "Calendar", calendar_path %></li>
    <%else %>
    <li><%= link_to "Sign-Up", new_user_registration_path %></li>
  <% end%>
</ul>

</navileft>

app/views/layouts/_registration.html.erb
<registration>
<div class="registrieren">

<%if user_signed_in? %>
  Signed up as <%= link_to current_user.email, show_path %>
<% else %>
Not signed-up yet? <%= link_to "Register now!", new_user_registration_path %> 
<%end%>
</div>
</registration>

app/views/layouts/_seitentitel.html.erb

--|Portalspass|--

app/views/layouts/_stylesheets.html.erb
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>


<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'mobile' if mobile_device? %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml">
<head>
  
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Portal | <%= @title %></title>
<%= render 'layouts/stylesheets' %>
<% if @title ==  "Deine Streams" %>
	<%= javascript_include_tag 'swfobject', "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
<% else %>
	<%= javascript_include_tag :defaults %>
<% end %>
</head>

<body>

<div class = "wrapper">
  <%= render 'layouts/header' %>
  <div class ="registration">
    <%=render 'layouts/registration' %>
  </div>
    <div class = "content">
      <div class="inner_content">
	      <div class = "navileft">
	        <%= render 'layouts/navileft' %>
	      </div>
	      <div class = "flash">
	      <% flash.each do |name, msg| %>
	        <%= content_tag :div, msg, :id => "flash_#{name}"%>
	      <%end%>
	      </div>
	        <div class = "text">
	        <%= yield %>
	        </div>
	    </div>
	  </div>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml">
<head>

<%= stylesheet_link_tag '/jqtouch/jqtouch.css', '/jqtouch/themes/apple/theme.css', 'mobile.css' %>
<%= javascript_include_tag '/jqtouch/jquery-1.4.2.min.js', '/jqtouch/jqtouch.js', 'mobile.js' %>

<title>Portal | <%= @title %></title>
<%= yield(:head) %>
</head>

<body>
	<div class="current">
		<div class="toolbar">
			<%= link_to "Back", root_url, :class => "back" unless current_page? root_path %>
			<h1><%= @title %></h1>
			<%= link_to 'Full Site', root_url(:mobile => 0), :class => "button", :rel => "external" %>
		</div>

		<%= yield %>
	</div>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1> About us </h1>

Diese Seite wurde von Julian Joswig, Dirk Kerber und Maximilian Woltersdorf erstellt.

app/views/pages/help.html.erb
<h1>Hilfe</h1>

<p>Hier wird Ihnen geholfen</p>

app/views/pages/help.mobile.erb
<ul>
	<li>This App was made by Dirk Kerber, Maximilian Woltersdorf and Julian Joswig.</li>
</ul>

app/views/pages/index.html.erb
<h1>Willkommen</h1>
<p>Die Site bietet euch verschiedene Dienste. Ihr k&ouml;nnt hier Nachrichten Feeds durchst&ouml;bern oder einen Kalender verwalten. Wir arbeiten im Ramen einer Hausarbeit im Bereich Webentwicklung.</p>
 

app/views/pages/index.mobile.erb
<ul>
	  <li><%= link_to "Home", index_path %></li>
      <%if user_signed_in?%>
	  <li><%= link_to "Dashboard", dashboard_path %></li>
      <li><%= link_to "Logout", destroy_user_session_path %></li>
      <% else %>
	  <li><%= link_to "Login", new_user_session_path %></li>
	  <% end %>
      <li><%= link_to "Help", help_path %></li>
      
</ul>

app/views/pages/stream.html.erb
<p class="navioben"><%= link_to "Anderes Zufallsvideo zeigen", stream_path %></p>
<!--
http://www.longtailvideo.com/support/jw-player/jw-player-for-flash-v5/12536/configuration-options
-->


<p><%= player({ :file => @video_path,
                :autostart => 'true',
                :skin=>'stijl'}) %></p>

app/views/users/show.html.erb

<p><h1> Hallo <b><%= current_user.email %></b> !</h1></p>

app/views/widgets/index.html.erb
<h1>Deine Dashboard-Widgets</h1>

<p class="navioben">
<%= link_to 'Neues Widget anlegen', new_widget_path %>
</p>

<table class = "widgettable">
<tr>
<th>Name</th>
<th>Typ</th>
<th>Quelle</th>
<th>Aktionen</th>
</tr>
<% @widgets.each do |w| %>
<tr>
<td><%= w.sourcename %></td>
<td><%= w.sourcetype.name %></td>
<td><%= w.sourceurl %></td>
<td><%= link_to 'Löschen', widget_path(w) , :method => :delete %></td>
</tr>
<% end %>
</table>

app/views/widgets/new.html.erb
<h1>Neues Widget anlegen</h1>

<fieldset>
<legend>W&auml;hle aus vordefinierten Quellen:</legend>  
<form>
Quellen: 
<select id="sourceTemplates" onchange="$('widget_sourceurl').value = $('sourceTemplates').value;">
	<option>--</option>
	<option value="http://www.heise.de/newsticker/heise.rdf">Heise.de Newsticker</option>
	<option value="http://www.ftd.de/rss2">Financial Times Deutschland</option>
	<option value="http://www.spiegel.de/schlagzeilen/tops/index.rss">Spiegel Online</option>
</select><br> <br>
</form></fieldset>

<br />

<fieldset>
<legend>Gebe geben Sie Ihre Quelle an: </legend>
<% form_for(@widget) do |f| %>
  <p>
    <%= f.label :sourcename, 'Name:' %> </label>
    <%= f.text_field :sourcename %>
  </p>
  <p>
    <%= f.label :sourceurl, 'URL der Quelle:' %></label>
    <%= f.url_field :sourceurl %>
  </p>
  <p>
    <%= f.label :sourcetype_id, 'Typ der Quelle:' %></label>
    <%= collection_select("widget", "sourcetype_id", @sourcetypes, :id, :name ) %>
</p>
</fieldset>
 <div class="actions">
    <%= f.submit "Anlegen" %>
  </div>
 
  

<% end %>